
DELIMITER //
CREATE OR REPLACE PROCEDURE DB_GENERAL.GET_BOT_SESSION_STATUS (
    IN V_USER_ID INT,
    OUT V_CODIGO INT,
    OUT V_RESULTADO VARCHAR(200)
)
BEGIN
    DECLARE V_ESTADO VARCHAR(50);
    DECLARE V_COUNT INT;

    -- VALIDAR SI EXISTE EL USUARIO EN LA TABLA EMPRESA
    SELECT COUNT(*) INTO V_COUNT
    FROM DB_GENERAL.TBL_EMPRESA
    WHERE EM_DETALLE = V_USER_ID;

    IF V_COUNT = 1 THEN
        -- OBTENER EL ESTADO DE LA SESIÓN
        SELECT EM_DETALLE7 INTO V_ESTADO
        FROM DB_GENERAL.TBL_EMPRESA
        WHERE EM_DETALLE = V_USER_ID;

        SET V_CODIGO = 0;
        SET V_RESULTADO = 'CONSULTA EXITOSA';

        -- RETORNAR EL ESTADO
        SELECT 
            Em_Codigo as ID,
            EM_DETALLE7 AS ESTADO_SESION
        FROM DB_GENERAL.TBL_EMPRESA
        WHERE EM_DETALLE = V_USER_ID;

    ELSEIF V_COUNT = 0 THEN
        SET V_CODIGO = 1;
        SET V_RESULTADO = 'USUARIO NO ENCONTRADO EN TABLA EMPRESA';
    ELSE
        SET V_CODIGO = 2;
        SET V_RESULTADO = 'ERROR: MÚLTIPLES REGISTROS ENCONTRADOS';
    END IF;

END
//

DELIMITER ;
