DELIMITER //
CREATE OR REPLACE PROCEDURE DB_GENERAL.UPDATE_PHONE_NUMBER (
    IN V_USER_ID INT,
    IN V_PHONE_NUMBER VARCHAR(20),
    OUT V_CODIGO INT,
    OUT V_RESULTADO VARCHAR(200)
)
BEGIN
    DECLARE V_COUNT INT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SET V_CODIGO = 500;
        SET V_RESULTADO = 'ERROR EN LA BASE DE DATOS';
    END;

    START TRANSACTION;

    -- VALIDAR SI EXISTE EL USUARIO EN LA TABLA EMPRESA
    SELECT COUNT(*) INTO V_COUNT
    FROM DB_GENERAL.TBL_EMPRESA
    WHERE EM_DETALLE = V_USER_ID;

    IF V_COUNT = 1 THEN
        -- ACTUALIZAR EL NÚMERO DE TELÉFONO
        UPDATE DB_GENERAL.TBL_EMPRESA
        SET EM_DETALLE8 = V_PHONE_NUMBER
        WHERE EM_DETALLE = V_USER_ID;

        SET V_CODIGO = 0;
        SET V_RESULTADO = 'NÚMERO ACTUALIZADO EXITOSAMENTE';
        COMMIT;

    ELSEIF V_COUNT = 0 THEN
        SET V_CODIGO = 1;
        SET V_RESULTADO = 'USUARIO NO ENCONTRADO EN TABLA EMPRESA';
        ROLLBACK;
    ELSE
        SET V_CODIGO = 2;
        SET V_RESULTADO = 'ERROR: MÚLTIPLES REGISTROS ENCONTRADOS';
        ROLLBACK;
    END IF;

END
//

DELIMITER ;