CREATE OR REPLACE DATABASE DB_GENERAL;

CREATE OR REPLACE TABLE DB_GENERAL.TBL_CREDENCIAL(
    CR_CODIGO INT PRIMARY KEY AUTO_INCREMENT,
    CR_EM_CODIGO INT NOT NULL,
    CR_NOMBRE_USUARIO VARCHAR(300) NOT NULL,
    CR_PASSWORD VARCHAR(900) NOT NULL,
    CR_PERFIL VARCHAR(100) NOT NULL,
    CR_TIPO_USUARIO VARCHAR(100) NOT NULL,
    CR_TIPO_CLIENTE VARCHAR(100) NOT NULL,
    CR_FECHA_CREACION DATETIME,
    CR_QUIEN_CREACION VARCHAR(50) NOT NULL,
    CR_FECHA_ACTUALIZACION DATETIME,
    CR_QUIEN_ACTUALIZACION VARCHAR(50),
    CR_ESTATUS VARCHAR(10) NOT NULL
);

DELIMITER $$

CREATE OR REPLACE TRIGGER DB_GENERAL.TBL_CREDENCIAL_BEFORE_INSERT
BEFORE INSERT ON TBL_CREDENCIAL
FOR EACH ROW
BEGIN
    SET NEW.CR_FECHA_CREACION = NOW();
END$$
DELIMITER ;


DELIMITER $$

CREATE OR REPLACE TRIGGER DB_GENERAL.TBL_CREDENCIAL_BEFORE_UPDATE
BEFORE UPDATE ON TBL_CREDENCIAL
FOR EACH ROW
BEGIN
    SET NEW.CR_FECHA_ACTUALIZACION = NOW();
END$$
DELIMITER ;

DELIMITER $$
CREATE TABLE DB_GENERAL.TBL_CREDENCIAL_HISTORICO AS
SELECT * FROM DB_GENERAL.TBL_CREDENCIAL WHERE 1=0$$
DELIMITER ;

DELIMITER $$

CREATE OR REPLACE TRIGGER DB_GENERAL.TR_CREDENCIAL_BEFORE_UPDATE
BEFORE UPDATE ON DB_GENERAL.TBL_CREDENCIAL
FOR EACH ROW
BEGIN
    INSERT INTO DB_GENERAL.TBL_CREDENCIAL_HISTORICO (
        CR_CODIGO,
        CR_EM_CODIGO,
        CR_NOMBRE_USUARIO,
        CR_PASSWORD,
        CR_PERFIL,
        CR_TIPO_USUARIO,
        CR_TIPO_CLIENTE,
        CR_FECHA_CREACION,
        CR_QUIEN_CREACION,
        CR_FECHA_ACTUALIZACION,
        CR_QUIEN_ACTUALIZACION,
        CR_ESTATUS
    )
    VALUES (
        OLD.CR_CODIGO,
        OLD.CR_EM_CODIGO,
        OLD.CR_NOMBRE_USUARIO,
        OLD.CR_PASSWORD,
        OLD.CR_PERFIL,
        OLD.CR_TIPO_USUARIO,
        OLD.CR_TIPO_CLIENTE,
        OLD.CR_FECHA_CREACION,
        OLD.CR_QUIEN_CREACION,
        OLD.CR_FECHA_ACTUALIZACION,
        OLD.CR_QUIEN_ACTUALIZACION,
        OLD.CR_ESTATUS
    );
END$$
DELIMITER ;

DELIMITER $$

CREATE OR REPLACE TABLE DB_GENERAL.TBL_PERMISOS(
PE_CODIGO INT PRIMARY KEY AUTO_INCREMENT,
PE_NOMBRE  VARCHAR(200),
PE_SEG_NOMBRE VARCHAR(200),
PE_APELLIDO VARCHAR(200),
PE_SEG_APELLIDO VARCHAR(200),
PE_TIPO_DOCUMENTO VARCHAR(50),
PE_DOCUMENTO VARCHAR(900),
PE_TELEFONS_FIJO VARCHAR(900),
PE_CEL VARCHAR(900),
PE_CORREO VARCHAR(900),
PE_DIRECCION VARCHAR(100),
PE_PERMISO VARCHAR(100),
PE_DEPARTAMENTO VARCHAR(100),
PE_CIUDAD VARCHAR(100),
PE_FECHA_NACIMIENTO VARCHAR(100),
PE_FECHA_CREACION DATETIME,
PE_USUARIO_CREACION VARCHAR(50) NOT NULL,
PE_FECHA_ACTUALIZACION DATETIME,
PE_USUARIO_ACTUALIZACION VARCHAR(50),
PE_ESTATUS VARCHAR(10) NOT NULL
)$$
DELIMITER ;

DELIMITER $$

CREATE OR REPLACE TABLE DB_GENERAL.TBL_PERMISOS_HISTORICO AS
SELECT * FROM DB_GENERAL.TBL_PERMISOS WHERE 1=0$$
DELIMITER ;

DELIMITER $$


CREATE OR REPLACE TRIGGER DB_GENERAL.TR_PERMISOS_BEFORE_UPDATE
BEFORE UPDATE ON DB_GENERAL.TBL_PERMISOS
FOR EACH ROW
BEGIN
    INSERT INTO DB_GENERAL.TBL_PERMISOS_HISTORICO (
        PE_CODIGO,
        PE_NOMBRE,
        PE_SEG_NOMBRE,
        PE_APELLIDO,
        PE_SEG_APELLIDO,
        PE_TIPO_DOCUMENTO,
        PE_DOCUMENTO,
        PE_TELEFONS_FIJO,
        PE_CEL,
        PE_CORREO,
        PE_DIRECCION,
        PE_PERMISO,
        PE_DEPARTAMENTO,
        PE_CIUDAD,
        PE_FECHA_NACIMIENTO,
        PE_FECHA_CREACION,
        PE_USUARIO_CREACION,
        PE_FECHA_ACTUALIZACION,
        PE_USUARIO_ACTUALIZACION,
        PE_ESTATUS
    )
    VALUES (
        OLD.PE_CODIGO,
        OLD.PE_NOMBRE,
        OLD.PE_SEG_NOMBRE,
        OLD.PE_APELLIDO,
        OLD.PE_SEG_APELLIDO,
        OLD.PE_TIPO_DOCUMENTO,
        OLD.PE_DOCUMENTO,
        OLD.PE_TELEFONS_FIJO,
        OLD.PE_CEL,
        OLD.PE_CORREO,
        OLD.PE_DIRECCION,
        OLD.PE_PERMISO,
        OLD.PE_DEPARTAMENTO,
        OLD.PE_CIUDAD,
        OLD.PE_FECHA_NACIMIENTO,
        OLD.PE_FECHA_CREACION,
        OLD.PE_USUARIO_CREACION,
        OLD.PE_FECHA_ACTUALIZACION,
        OLD.PE_USUARIO_ACTUALIZACION,
        OLD.PE_ESTATUS
    );
END$$
DELIMITER ;

DELIMITER $$

CREATE OR REPLACE TRIGGER DB_GENERAL.TBL_PERMISOS_BEFORE_INSERT
BEFORE INSERT ON DB_GENERAL.TBL_PERMISOS
FOR EACH ROW
BEGIN
    SET NEW.PE_FECHA_CREACION = NOW();
END$$

DELIMITER ;

DELIMITER $$

CREATE OR REPLACE TRIGGER DB_GENERAL.TBL_PERMISOS_BEFORE_UPDATE
BEFORE UPDATE ON DB_GENERAL.TBL_PERMISOS
FOR EACH ROW
BEGIN
    SET NEW.PE_FECHA_ACTUALIZACION = NOW();
END$$

DELIMITER ;

DELIMITER $$

CREATE OR REPLACE TABLE DB_GENERAL.TBL_EMPRESA(
    EM_CODIGO INT PRIMARY KEY AUTO_INCREMENT,
    EM_DETALLE VARCHAR(200),
    EM_DETALLE1 VARCHAR(200),
    EM_DETALLE2 VARCHAR(200),
    EM_DETALLE3 VARCHAR(200),
    EM_DETALLE4 VARCHAR(200),
    EM_DETALLE5 VARCHAR(200),
    EM_DETALLE6 VARCHAR(200),
    EM_DETALLE7 VARCHAR(200),
    EM_DETALLE8 VARCHAR(200),
    EM_DETALLE9 VARCHAR(200),
    EM_DETALLE10 VARCHAR(200),
    EM_FECHA_CREACION DATETIME,
    EM_USUARIO_CREACION VARCHAR(50) NOT NULL,
    EM_FECHA_ACTUALIZACION DATETIME,
    EM_USUARIO_ACTUALIZACION VARCHAR(50),
    EM_ESTATUS VARCHAR(10) NOT NULL
)$$

DELIMITER ;

DELIMITER $$

CREATE TABLE DB_GENERAL.TBL_EMPRESA_HISTORICO AS
SELECT * FROM DB_GENERAL.TBL_EMPRESA WHERE 1=0$$

DELIMITER ;

DELIMITER $$

CREATE OR REPLACE TRIGGER DB_GENERAL.TR_EMPRESA_BEFORE_UPDATE
BEFORE UPDATE ON DB_GENERAL.TBL_EMPRESA
FOR EACH ROW
BEGIN
    INSERT INTO DB_GENERAL.TBL_EMPRESA_HISTORICO (
        EM_CODIGO,
        EM_DETALLE,
        EM_DETALLE1,
        EM_DETALLE2,
        EM_DETALLE3,
        EM_DETALLE4,
        EM_DETALLE5,
        EM_DETALLE6,
        EM_DETALLE7,
        EM_DETALLE8,
        EM_DETALLE9,
        EM_DETALLE10,
        EM_FECHA_CREACION,
        EM_USUARIO_CREACION,
        EM_FECHA_ACTUALIZACION,
        EM_USUARIO_ACTUALIZACION,
        EM_ESTATUS
    )
    VALUES (
        OLD.EM_CODIGO,
        OLD.EM_DETALLE,
        OLD.EM_DETALLE1,
        OLD.EM_DETALLE2,
        OLD.EM_DETALLE3,
        OLD.EM_DETALLE4,
        OLD.EM_DETALLE5,
        OLD.EM_DETALLE6,
        OLD.EM_DETALLE7,
        OLD.EM_DETALLE8,
        OLD.EM_DETALLE9,
        OLD.EM_DETALLE10,
        OLD.EM_FECHA_CREACION,
        OLD.EM_USUARIO_CREACION,
        OLD.EM_FECHA_ACTUALIZACION,
        OLD.EM_USUARIO_ACTUALIZACION,
        OLD.EM_ESTATUS
    );
END$$

DELIMITER ;

DELIMITER $$

CREATE OR REPLACE TRIGGER DB_GENERAL.TBL_EMPRESA_BEFORE_INSERT
BEFORE INSERT ON DB_GENERAL.TBL_EMPRESA
FOR EACH ROW
BEGIN
    SET NEW.EM_FECHA_CREACION = NOW();
END$$

DELIMITER ;

DELIMITER $$

CREATE OR REPLACE TRIGGER DB_GENERAL.TBL_EMPRESA_BEFORE_UPDATE
BEFORE UPDATE ON DB_GENERAL.TBL_EMPRESA
FOR EACH ROW
BEGIN
    SET NEW.EM_FECHA_ACTUALIZACION = NOW();
END$$

DELIMITER ;

DELIMITER $$

CREATE OR REPLACE TABLE DB_GENERAL.TBL_GESTOR_MENSAJE (
    GS_CODIGO INT PRIMARY KEY AUTO_INCREMENT,
    GS_DETALLE VARCHAR(500),
    GS_DETALLE1 VARCHAR(500),
    GS_DETALLE2 VARCHAR(500),
    GS_DETALLE3 VARCHAR(500),
    GS_DETALLE4 VARCHAR(500),
    GS_DETALLE5 VARCHAR(500),
    GS_DETALLE6 VARCHAR(500),
    GS_DETALLE7 VARCHAR(500),
    GS_DETALLE8 VARCHAR(500),
    GS_DETALLE9 VARCHAR(500),
    GS_DETALLE10 VARCHAR(500),
    GS_DETALLE11 VARCHAR(500),
    GS_DETALLE12 VARCHAR(500),
    GS_DETALLE13 VARCHAR(500),
    GS_DETALLE14 VARCHAR(500),
    GS_DETALLE15 VARCHAR(500),
    GS_DETALLE16 VARCHAR(500),
    GS_DETALLE17 VARCHAR(500),
    GS_DETALLE18 VARCHAR(500),
    GS_DETALLE19 VARCHAR(500),
    GS_DETALLE20 VARCHAR(500),
    GS_FECHA_CREACION  DATETIME,
    GS_USUARIO_CREACION  VARCHAR(50) NOT NULL,
    GS_FECHA_ACTUALIZACION  DATETIME,
    GS_USUARIO_ACTUALIZACION  VARCHAR(50),
    GS_ESTATUS  VARCHAR(10) NOT NULL
)$$

DELIMITER ;


-- CREATE TRIGGER FOR INSERT
DELIMITER $$

CREATE OR REPLACE TRIGGER DB_GENERAL.TBL_GESTOR_MENSAJE_BEFORE_INSERT
BEFORE INSERT ON TBL_GESTOR_MENSAJE
FOR EACH ROW
BEGIN
    SET NEW.GS_FECHA_CREACION = NOW();
END$$

DELIMITER ;

-- CREATE TRIGGER FOR UPDATE
DELIMITER $$

CREATE OR REPLACE TRIGGER DB_GENERAL.TBL_GESTOR_MENSAJE_BEFORE_UPDATE 
BEFORE UPDATE ON TBL_GESTOR_MENSAJE
FOR EACH ROW
BEGIN
    SET NEW.GS_FECHA_ACTUALIZACION = NOW();
END$$

DELIMITER ;

DELIMITER $$

-- CREATE HISTORY TABLE
CREATE TABLE DB_GENERAL.TBL_GESTOR_MENSAJE_HISTORICO AS
SELECT * FROM DB_GENERAL.TBL_GESTOR_MENSAJE WHERE 1=0$$

DELIMITER ;


DELIMITER $$

CREATE OR REPLACE TRIGGER DB_GENERAL.TR_GESTOR_MENSAJE_BEFORE_UPDATE
BEFORE UPDATE ON DB_GENERAL.TBL_GESTOR_MENSAJE
FOR EACH ROW
BEGIN
    INSERT INTO DB_GENERAL.TBL_GESTOR_MENSAJE_HISTORICO (
        GS_CODIGO,
        GS_DETALLE,
        GS_DETALLE1,
        GS_DETALLE2,
        GS_DETALLE3,
        GS_DETALLE4,
        GS_DETALLE5,
        GS_DETALLE6,
        GS_DETALLE7,
        GS_DETALLE8,
        GS_DETALLE9,
        GS_DETALLE10,
        GS_DETALLE11,
        GS_DETALLE12,
        GS_DETALLE13,
        GS_DETALLE14,
        GS_DETALLE15,
        GS_DETALLE16,
        GS_DETALLE17,
        GS_DETALLE18,
        GS_DETALLE19,
        GS_DETALLE20,
        GS_FECHA_CREACION,
        GS_USUARIO_CREACION,
        GS_FECHA_ACTUALIZACION,
        GS_USUARIO_ACTUALIZACION,
        GS_ESTATUS
    )
    VALUES (
        OLD.GS_CODIGO,
        OLD.GS_DETALLE,
        OLD.GS_DETALLE1,
        OLD.GS_DETALLE2,
        OLD.GS_DETALLE3,
        OLD.GS_DETALLE4,
        OLD.GS_DETALLE5,
        OLD.GS_DETALLE6,
        OLD.GS_DETALLE7,
        OLD.GS_DETALLE8,
        OLD.GS_DETALLE9,
        OLD.GS_DETALLE10,
        OLD.GS_DETALLE11,
        OLD.GS_DETALLE12,
        OLD.GS_DETALLE13,
        OLD.GS_DETALLE14,
        OLD.GS_DETALLE15,
        OLD.GS_DETALLE16,
        OLD.GS_DETALLE17,
        OLD.GS_DETALLE18,
        OLD.GS_DETALLE19,
        OLD.GS_DETALLE20,
        OLD.GS_FECHA_CREACION,
        OLD.GS_USUARIO_CREACION,
        OLD.GS_FECHA_ACTUALIZACION,
        OLD.GS_USUARIO_ACTUALIZACION,
        OLD.GS_ESTATUS
    );
END$$

DELIMITER ;